title: Israel Musicians for Peace
email:
description: >-
  An open letter from Israeli composers and musicians
baseurl: ""
url: "https://israelmusiciansforpeace.com" # Replace with actual domain
twitter_username: none
github_username: juilie
author: Israel Musicians for Peace

plugins:
  - jekyll-feed

include:
  - static

collections:
  letter:
    output: false
  signatories:
    output: false